import { motion } from 'framer-motion'
import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { trpc } from '@/utils/trpc'

const Container = styled(motion.div)`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 100%;
  font-weight: bold;
  font-size: 2rem;
`

const FlexRow = styled(motion.div)`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  width: 100%;
`

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["hello"])
  return (
    <Container>
      <Head>
        <title>Trpc Demo</title>
        <meta name="description" content="Generated by G0Dz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlexRow
        initial={{
          opacity: 0,
          y: 100,
        }}
        animate={{
          opacity: 1,
          y: 0,
        }}>
        {data?.greeting}
      </FlexRow>
    </Container>
  )
}

export default Home
